version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - DEMO_MODE=true
      - JWT_SECRET=dev-secret
      - OIDC_ISSUER=demo-issuer
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend:8000
      - BACKEND_URL=http://backend:8000
      - NEXT_PUBLIC_BACKEND_WS=ws://localhost:8000/ws/sim
      - NEXT_PUBLIC_DEMO_MODE=true
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=demo
      - POSTGRES_DB=rail_demo
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./scripts/sql:/docker-entrypoint-initdb.d
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  db_data:
